// <auto-generated />
using Clearmind.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clearmind.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231031140402_02")]
    partial class _02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clearmind.Models.Entidades.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(300)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Objetivos", "public");
                });

            modelBuilder.Entity("Clearmind.Models.Entidades.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nchar(200)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos", "public");
                });

            modelBuilder.Entity("Clearmind.Models.Entidades.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(300)");

                    b.Property<int>("ObjetivoID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tareas", "public");
                });

            modelBuilder.Entity("Clearmind.Models.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nchar(270)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "public");
                });

            modelBuilder.Entity("Clearmind.Models.Entidades.UsuarioProyecto", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("ProyectoID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("UsuarioID", "ProyectoID");

                    b.ToTable("UsuariosProyectos", "public");
                });

            modelBuilder.Entity("Clearmind.Models.Entidades.UsuarioTarea", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("TareaID")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("UsuarioID", "TareaID");

                    b.ToTable("UsuariosTareas", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
